language: clojure # node_js
sudo: required  
dist: trusty
services:
  - mysql
before_install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install -g coffee-script
  - coffee -o . -cb src
  - ls
  - pwd
  - npm install wdio-mocha-framework

  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0 
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb

  - "sudo apt-get remove mysql-common mysql-server-5.5 mysql-server-core-5.5 mysql-client-5.5 mysql-client-core-5.5"
  - "sudo apt-get autoremove"
  - "sudo apt-get install libaio1"
  - "wget -O mysql-5.6.14.deb http://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.14-debian6.0-x86_64.deb/from/http://cdn.mysql.com/"
  - "sudo dpkg -i mysql-5.6.14.deb"
  - "sudo cp /opt/mysql/server-5.6/support-files/mysql.server /etc/init.d/mysql.server"
  - "sudo ln -s /opt/mysql/server-5.6/bin/* /usr/bin/"
  # some config values were changed since 5.5
  - "sudo sed -i'' 's/table_cache/table_open_cache/' /etc/mysql/my.cnf"
  - "sudo sed -i'' 's/log_slow_queries/slow_query_log/' /etc/mysql/my.cnf"
  - "sudo sed -i'' 's/basedir[^=]\\+=.*$/basedir = \\/opt\\/mysql\\/server-5.6/' /etc/mysql/my.cnf"
  - "sudo /etc/init.d/mysql.server start"

  # - wget http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip
  # - unzip chromedriver_linux64.zip -d /home/travis/build/
  # - export CHROME_BIN=chromium-browser
  # - "export DISPLAY=:99.0"
  # - "sh -e /etc/init.d/xvfb start"
  # - sleep 3
  
  - npm install chromedriver
  - cd ../
  - git clone git@github.com:Purple-Services/common.git
  - cd common
  - lein install
  - cd ../
  - git clone git@github.com:Purple-Services/opt.git
  - cd opt
  - lein install
  - cd ../
  - git clone git@github.com:Purple-Services/app-service.git
  - cd app-service
  - mysql -e "DROP DATABASE if exists ebdb;" -uroot
  - mysql -e "DROP DATABASE if exists ebdb_test;" -uroot
  - mysql -e "create database if not exists ebdb;" -uroot
  - mysql -e "create database if not exists ebdb_test;" -uroot
  - lein exec -p scripts/setupdb.clj root_password=
  - lein with-profile app-integration-test ring server &
  - ls
  - (cd ../app; java -jar selenium-server-standalone-2.53.0.jar &)
script:
  - ls
  - (cd ../app/test; ls; node -v; npm -v; npm install; node_modules/.bin/wdio --suite GasPrice)

env:
  - TRAVIS_NODE_VERSION="0.12"
# global:
#   - CXX=g++-4.8
#   - NODE_ENV=development

  