language: clojure
sudo: required  
dist: trusty
addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
before_install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install -g coffee-script
  - coffee -o . -cb src
  - ls
  - pwd
  - npm install wdio-mocha-framework
  - sudo npm install http-server -g

  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0 
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  
  - npm install chromedriver
  - cd ../
  - git clone git@github.com:Purple-Services/common.git
  - cd common
  - lein install
  - cd ../
  - git clone git@github.com:Purple-Services/opt.git
  - cd opt
  - lein install
  - cd ../
  - git clone git@github.com:Purple-Services/app-service.git
  - cd app-service
  - mysql -e "DROP DATABASE if exists ebdb;" -uroot
  - mysql -e "DROP DATABASE if exists ebdb_test;" -uroot
  - mysql -e "create database if not exists ebdb;" -uroot
  - mysql -e "create database if not exists ebdb_test;" -uroot
  - lein exec -p scripts/setupdb.clj root_password=
  - lein with-profile app-integration-test ring server &
  - (cd ../app; java -jar selenium-server-standalone-2.53.0.jar &)
  - (cd ../app; http-server -o --cors &)
script:
  - (cd ../app/test; ls; node -v; npm -v; npm install; node_modules/.bin/wdio --suite GasPrice)

env:
  - TRAVIS_NODE_VERSION="0.12"
  
# global:
#   - CXX=g++-4.8
#   - NODE_ENV=development

notifications:
  slack:
    rooms:
      - purpledelivery:LSIV4jgY6MoQMOWpAr6nnpo7#github
    on_success: always
    on_failure: always
  email: false
  