language: clojure # node_js
before_install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install -g coffee-script
  - coffee -o . -cb src
  - npm install wdio-mocha-framework
  - sh -e /etc/init.d/xvfb start
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - cd ../
  - git clone git@github.com:Purple-Services/common.git
  - cd common
  - lein install
  - cd ../
  - git clone git@github.com:Purple-Services/opt.git
  - cd opt
  - lein install
  - cd ../
  - git clone git@github.com:Purple-Services/app-service.git
  - cd app-service
  - mysql -e "DROP DATABASE if exists ebdb;" -uroot
  - mysql -e "DROP DATABASE if exists ebdb_test;" -uroot
  - mysql -e "create database if not exists ebdb;" -uroot
  - mysql -e "create database if not exists ebdb_test;" -uroot
  - lein exec -p scripts/setupdb.clj root_password=
  - lein with-profile app-integration-test ring server &
  - ls
  - (cd ../app; java -jar selenium-server-standalone-2.53.0.jar &)
script:
  - ls
  - (cd ../app/test; ls; node -v; npm -v; npm install; node_modules/.bin/wdio --suite GasPrice)

env:
  - TRAVIS_NODE_VERSION="0.12"
# global:
#   - CXX=g++-4.8
#   - NODE_ENV=development

  